name: acceptance dt
values:
  - key: HOST
    value: ''
  - key: INSTANCE
    value: ''
  - key: BASE_URI
    value: ''
  - key: ENVIRONMENT
    value: ''
  - key: PATH
    value: ''
  - key: HC_token
    value: qHf68VyMGqjjTvr3a2OMdZjfT25pB2h0
color: 240
