name: acceptance dt
values:
  - key: HOST
    value: ''
  - key: INSTANCE
    value: ''
  - key: BASE_URI
    value: ''
  - key: ENVIRONMENT
    value: ''
  - key: PATH
    value: ''
  - key: HC_token
    value: "dummy-token-3"
color: 240
