name: acceptance fx
values:
  - key: HOST
    value: https
  - key: INSTANCE
    value: ''
  - key: BASE_URI
    value: ''
  - key: ENVIRONMENT
    value: ''
  - key: PATH
    value: ''
  - key: HC_token
    value: "dummy-token-4"
color: 180
